### ISSUE TITLE
Admin: The path to edit a user is missing a `/`

### ISSUE THREAD

**Issue by yoannfleurydev** [BearStudio/start-ui#47]
I am on `/app/admin/users` and I click on the three dots to edit a user, the link is incorrect and missing a `/` so I am now on a 404.

![image](https://user-images.githubusercontent.com/3920615/114686791-663ac880-9d13-11eb-80bb-a8033e708e96.png)

**Comment by ivan-dalmet** [comment]
Fixed by #48
