### ISSUE TITLE
Add CI (GitHub Actions)

### ISSUE THREAD

**Issue by yoannfleurydev** [BearStudio/start-ui#71]
It could be great to add a CI pipeline to check for the types and the tests.

- `yarn tsc --noEmit`
- `yarn test`

**Comment by LaghzaliTaha** [comment]
Hello Yoann,
I took the action for this issue and I hope that I can enhance and contribute to your open-source project.

Here is the link for review: https://github.com/BearStudio/start-ui/pull/72

**Comment by yoannfleurydev** [comment]
Thanks again a lot for your time and for the PR, I'm closing this issue as #72 matches the criteria.
